---
name: pre-commit

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
    - name: install shfmt
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        curl -L -s -o $GITHUB_WORKSPACE/bin/shfmt https://github.com/mvdan/sh/releases/download/v3.1.2/shfmt_v3.1.2_linux_amd64
        chmod +x $GITHUB_WORKSPACE/bin/shfmt
        curl -L -S -o $GITHUB_WORKSPACE/bin/tfsec https://github.com/liamg/tfsec/releases/download/v0.24.1/tfsec-linux-amd64
        chmod +x $GITHUB_WORKSPACE/bin/tfsec
        echo "::add-path::$GITHUB_WORKSPACE/bin"
    - uses: pre-commit/action@v2.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
